# Generated by Django 3.2.8 on 2022-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
