# Generated by Django 3.2.8 on 2022-02-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_users_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='articles',
        ),
    ]
