# Generated by Django 3.2.8 on 2022-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_users_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '浏览文章信息', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelTable(
            name='articles',
            table='blog_users',
        ),
    ]
