# Generated by Django 3.2.8 on 2022-02-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220219_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='匿名', max_length=10)),
                ('content', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
