# Generated by Django 3.2.8 on 2022-02-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='artid',
            field=models.IntegerField(default=0),
        ),
    ]
